name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-mock

      - name: Run linter (flake8)
        run: |
          flake8 src/ tests/ --max-line-length=120 --extend-ignore=E203,E501

      - name: Run tests with pytest
        run: |
          pytest tests/ -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker container
        run: |
          docker-compose up -d
          sleep 15  # Increased to 15 seconds for container startup

      - name: Check container logs
        run: docker-compose logs

      - name: Check API health
        run: |
          curl -f http://localhost:8000/ || exit 1
          curl -f -X POST -H "Content-Type: application/json" -d '{"Amount_woe": -0.34, "trans_hour_woe": 0.12, "total_amount": 500.0, "avg_amount": 50.0, "trans_count": 10.0, "amount_std": 20.0, "trans_day": 15.0, "trans_month": 6.0, "trans_year": 2025.0, "CurrencyCode_UGX": 1.0, "ProviderId_ProviderId_1": 1.0, "ProductId_ProductId_1": 1.0, "ProductCategory_airtime": 1.0, "ChannelId_ChannelId_1": 1.0}' http://localhost:8000/predict || exit 1

      - name: Stop Docker container
        if: always()
        run: docker-compose down
