name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13.3
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest jupyter nbconvert  # Keep nbconvert for future use

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests (placeholder)
        run: |
          echo "No tests yet; add pytest commands for Task 3+"

    # Temporarily disable notebook execution until data handling is resolved
    # - name: Verify notebook execution
    #   env:
    #     CI: "true"
    #   run: |
    #     jupyter nbconvert --to notebook --execute notebooks/eda.ipynb --inplace --ExecutePreprocessor.timeout=600
    #     # Check if the notebook runs without errors
